version: "3.3"

services:

  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: echo `db.runCommand('ping').ok` | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: API
    volumes:
      - mongo:/data:/data/db
    networks:
      - api

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_USER: root
      REDIS_PASSWORD: root
      REDIS_DATABASE: API
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - api

  api:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    networks:
      - api
    volumes:
      - .:/usr/src/app

networks:
  api:

volumes:
  mongo:
  redis: